id: P004189
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1CZ690
  title: དཔྱད་རྩོམ་ཕྱོགས་བསྒྲིགས
  author: ''
  volumes:
    2628ae9399284f9da89ed5fdd9997c91:
      image_group_id: I1GS66298
      title: ''
      volume_number: 1
      total_pages: 469
      base_file: v001.txt
